seed_everything: 42
trainer:
  max_epochs: 35
  accelerator: "gpu"
  devices: [0]
  strategy: "auto"
  precision: "32-true"  # single-precision training
  accumulate_grad_batches: 2
  callbacks:
    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
      init_args:
        save_weights_only: false
        mode: "min"
        monitor: "val_loss"
        every_n_train_steps: 0
        every_n_epochs: 1
        train_time_interval: null
    - class_path: lightning.pytorch.callbacks.EarlyStopping
      init_args:
        monitor: "val_loss"
        min_delta: 0.0
        patience: 4
        verbose: false
  logger:
    - class_path: lightning.pytorch.loggers.TensorBoardLogger
      init_args:
        save_dir: "."
        name: "toptagging_checkpoints"

model:
  class_path: models.models.JetTaggingModule
  init_args:
    in_channels: 11
    u_channels: 6
    embed_dim: 32
    attn: "plain"
    max_num_particles: 128
    num_blocks: 4
    num_heads:  32
    num_classes: 1
    lr: 0.0015
    t_max: 35
    eta_min: 1e-6
    batch_size: 128

data:
  class_path: data.data_handling.JetTaggingDataModule
  init_args:
    data_dir: "/mnt/d/waleed/CP-Higgs/GraphTransformer/GraphTransformer/"
    file_list: ["test_graph.h5", "test_graph.h5", "test_graph.h5"]
    batch_size: 128
    num_workers: 16

